MusicShop/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MusicShop.DataAccess.Repository.IRepository;
using MusicShop.Models;


namespace Traditional_Cloth_Shop_App.Areas.Admin.Controllers
{

    [Area("Admin")]
    //[Authorize(Roles = StaticData.Role_Admin)]
    public class CompanyController : Controller
    {


        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Companies> companies = _unitOfWork.Company.GetAll().ToList();
            return View(companies);
        }

       

     

        public IActionResult Upsert(int? id)
        {

           
       
            if (id == null || id == 0)
            {
                return View(new Companies());
            }
            else
            {
                Companies company=_unitOfWork.Company.GetFirstOrDefault(u=>u.Id == id);

                return View(company);
            }


        }


        [HttpPost]

        public IActionResult Upsert(Companies NewCompany)
        {
            if (ModelState.IsValid)
            {
                if(NewCompany.Id == 0) 
                {
                
                 _unitOfWork.Company.Add(NewCompany);
                
                }
                else
                {
                    _unitOfWork.Company.Upadate(NewCompany);    
                }

                _unitOfWork.Save();
                TempData["success"] = "Company Created Successfully";
                return RedirectToAction("Index");   

            }
            else
            {
                return View(NewCompany);
            }

        }

        #region ApiCall
        [HttpGet]
        public IActionResult GetAll()
        {

            List<Companies> CompanyList = _unitOfWork.Company.GetAll().ToList();



            return Json(new { data = CompanyList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var companytodelete=_unitOfWork.Company.GetFirstOrDefault(u=>u.Id==id);

            if (companytodelete == null)
            {
                return Json(new {success= false, message="Faild to delete company"});
            }

            _unitOfWork.Company.Remove(companytodelete);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Company deleted Successfully" });
        }


        #endregion

    }


}

MusicShop/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MusicShop.DataAccess.Repository.IRepository;
using MusicShop.Models;
using MusicShop.ViewModels;

namespace Traditional_Cloth_Shop_App.Areas.Admin.Controllers
{

    [Area("Admin")]
    //[Authorize(Roles = StaticData.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {

            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {

            List<Product> productsList = _unitOfWork.Product.GetAll(includeProperties:"Category").ToList();
           

            
            return View(productsList);
        }

        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
           {
               CategoryList =_unitOfWork.Category.GetAll().Select(u=>new SelectListItem
               {
                   Text = u.Name,
                   Value=u.Id.ToString()
               }),

             Product = new Product()
           };
           if(id==null || id == 0)
            {
                return View(productVM);
            }
            else
            {
                productVM.Product=_unitOfWork.Product.GetFirstOrDefault(u=>u.Id==id);

                return View(productVM);
            }
          

        }

        [HttpPost]  

        public IActionResult Upsert(ProductVM Newproduct,IFormFile? file)
        {
            if(ModelState.IsValid)
            {
                string wwwRootPath=_webHostEnvironment.WebRootPath;

                if(file!=null) 
                { 
                  string fileName=Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                  string productPath=Path.Combine(wwwRootPath,@"images\product");

                    if(!string.IsNullOrEmpty(Newproduct.Product.ImageUrl))
                    {
                        var oldImagePath=Path.Combine(wwwRootPath,Newproduct.Product.ImageUrl.Trim('\\'));

                        if(System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var filStream=new FileStream(Path.Combine(productPath,fileName), FileMode.Create))
                    {
                        file.CopyTo(filStream); 
                    }

                    Newproduct.Product.ImageUrl = @"\images\product\" + fileName;
                
                }

                if(Newproduct.Product.Id==0)
                {

                    _unitOfWork.Product.Add(Newproduct.Product);
                }
                else
                {
                    _unitOfWork.Product.Upadate(Newproduct.Product);
                }

                _unitOfWork.Save();
                TempData["success"] = "Procucte created Successfully";
                return RedirectToAction("Index");   
            }
            else
            {

                Newproduct.CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });

                return View(Newproduct);

            }

                
            
          
        }

       
        #region ApiCalls

        [HttpGet]

        public IActionResult GetAll()
        {

            List<Product> productsList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();



            return Json(new {data=productsList});
        }

        [HttpDelete]

        public IActionResult Delete(int? id)
        {

            var producttodelete = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);

            if (producttodelete==null)
            {
                return Json(new { success = false, message = "Error While Deleting" });
            }

            var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, 
                producttodelete.ImageUrl.Trim('\\'));

            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWork.Product.Remove(producttodelete);
            _unitOfWork.Save();


            return Json(new { success = true, message="Product Deleted Successfully" });
        }

        #endregion
    }
}

MusicShop/ViewComponents/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MusicShop.DataAccess.Repository.IRepository;
using MusicShop.Utility;
using System.Security.Claims;
using System.Web.Providers.Entities;

namespace MusicShop.ViewComponents
{
    public class ShoppingCartViewComponent:ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(StaticData.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(StaticData.SessionCart,
                  _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).Count());
                }

                return View(HttpContext.Session.GetInt32(StaticData.SessionCart));
            }
            else
            {

                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

MusicShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Traditional_Cloth_Shop_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/Traditional_Cloth_Shop_App.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.1.3/css/dataTables.dataTables.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MusicShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                        </li>
                        @* @if (User.IsInRole(StaticData.Role_Admin) || User.IsInRole(StaticData.Role_Employee))
                        { *@
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin Panel
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item " asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item " asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="dropdown-item " asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>

                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item " asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item " asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                    </li>
                                </ul>
                            </li>
                       @*  } *@


                        <li class="nav-item">
                            @* <a class="nav-link " asp-area="Customer" asp-controller="Cart" asp-action="Index">

                                @await Component.InvokeAsync("ShoppingCart")
                            </a> *@
                        </li>



                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-light text-center">
        <div class="container">
            &copy; 2024 - 404 NotFound Developers LLC
        </div>
    </footer>



    <!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap JS -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Site-specific JS -->
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- SweetAlert2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- DataTables -->
    <script src="//cdn.datatables.net/2.1.3/js/dataTables.min.js" asp-append-version="true"></script>

    <!-- TinyMCE -->
    <script src="https://cdn.tiny.cloud/1/6px0ckipd17qghxkwh3b1ffc41i4a0qhkvvesmqjejcvkbu9/tinymce/7/tinymce.min.js" referrerpolicy="origin"> <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script></script>

    <!-- Toastr -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MusicShop/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}